language: go

go:
  - 1.4
  - 1.5

install:
  - go get github.com/cloudfoundry/cli/cf
  - (cd $GOPATH/src/github.com/cloudfoundry/cli && ./bin/generate-language-resources)
  - go get ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get golang.org/x/tools/cmd/cover

script: ./scripts/test.sh
